httpProxy: "http://127.0.0.1:12716"
httpsProxy: "http://127.0.0.1:12716"
nodeLinker: node-modules
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
yarnPath: .yarn/releases/yarn-3.1.0-rc.11.cjs
